#!/bin/sh
echo "`date` $@" | tee -a /tmp/service.log
case "$1$2" in
    'mcollectiverestart')
        /opt/puppetlabs/puppet/bin/mcollectived --config=/etc/puppetlabs/mcollective/server.cfg --pidfile=/var/run/puppetlabs/mcollective.pid --daemonize
        sleep 70
    ;;
    'pe-activemqrestart')
        export JAVA_HOME=/opt/puppetlabs/server/apps/java/lib/jvm/java/jre
        . /etc/sysconfig/pe-activemq && \
        /opt/puppetlabs/server/apps/activemq/bin/pe-activemq start
        sleep 70
    ;;
    'pe-puppetserverstart')
        INSTALL_DIR="/opt/puppetlabs/server/apps/puppetserver"
        JAVA_ARGS="-Xms512m -Xmx512m"
        CONFIG="/etc/puppetlabs/puppetserver/conf.d"
        BOOTSTRAP_CONFIG="/etc/puppetlabs/puppetserver/bootstrap.cfg"
        /opt/puppetlabs/server/bin/java $JAVA_ARGS \
              '-XX:OnOutOfMemoryError=kill -9 %%p' \
              -Djava.security.egd=/dev/urandom \
              -cp "${INSTALL_DIR}/puppet-server-release.jar" clojure.main \
              -m puppetlabs.trapperkeeper.main \
              --config "${CONFIG}" \
              -b "${BOOTSTRAP_CONFIG}" &
        sleep 70
    ;;
    'pe-postgresql.*start')
        Environment=PGDATA=/opt/puppetlabs/server/data/postgresql/9.4/data
        Environment=PGSTARTUPLOG=/var/log/puppetlabs/postgresql/pgstartup.log
        /opt/puppetlabs/server/apps/postgresql/bin/postgresql-check-db-dir ${PGDATA} && \
        /opt/puppetlabs/server/apps/postgresql/bin/pg_ctl start -D ${PGDATA} --log ${PGSTARTUPLOG} \
            -o "-c log_directory='/var/log/puppetlabs/postgresql'" -s -w -t 300
    ;;
    *)
    exit
    ;;
esac

